name: GLSL Validator
on: [push]
jobs:
  Validate-GLSL:
    name: GLSL Validator
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Download GLSL Validator release
        uses: Itsblue/download-release-assets-action@v1
        with:
          repo: "KhronosGroup/glslang"
          version: "tags/master-tot"
          file: "glslang-master-linux-Release.zip"
      - name: Decompress
        uses: TonyBogdanov/zip@1.0
        with:
          args: unzip -qq ./glslang-master-linux-Release.zip -d ./validator
      - name: Validate fragment shaders
        run: ./validator/bin/glslangValidator ./fragment/**/**.frag
# enable whenever theres vertex shaders in the repo
#      - name: Validate vertex shaders
#        run: ./validator/bin/glslangValidator ./vertex/**/**.vert
